### ISSUE TITLE
JOSS submission todo

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/blimpy#101]
We've submitted blimpy to the Journal of Open Source Software, and the reviewer has had a look at our code and made some useful suggestions. These are summarized here, so we can tick them off as we deal with them.

## General
 - [x] Confirm author list (add Yuhong and Mark, add acknowledgements)
 - [x] Harmonize PyPi and github versions so they match (e.g. both at 1.4.0)

## Software Paper
 - [x] The paper is very short. It would be nice if you could elaborate a bit more (e.g., what exactly you're looking for in the data, what is a "waterfall" file, etc.).
 - [x] The references don't display correctly in the PDF proof. This might be an issue with the formatting of the paper.bib file.
 - [x] The Croft:2016 reference has a DOI listed online that is missing from the paper.bib file (10.13140/RG.2.2.10561.20326). Also, this is not a published article. It should be listed as a techreport or unpublished, and include a URL to the paper. researchgate.net also shouldn't be listed as the journal name.
- [ ] I wasn't able to find a software archive for Blimpy.
- [x] Typos in paper.md:  avaiable -> available, guppi -> GUPPI, astromers -> astronomers, endeavour -> endeavor

## Documentation

- [x] The project API is very difficult to read/navigate. Most functions and methods are missing argument descriptions.
- [x] The examples are very limited. The only examples that I could find are in README.md, but they only really show how to import data.
- [x] In README.md, it says "This readme is far from complete. If you have any request/questions please lets us know!". The REAME should be expanded.
- [x] Overall, I'm finding it very difficult to begin using the software with the current level of documentation.

**Comment by telegraphic** [comment]
I'm working through these. 

@marksbrt and @FX196 , are you able to address the README.md?

@jeenriquez -- I know you're busy these next weeks, main thing to do is check you're happy with the `paper.md` and suggest any changes. I generated a [PDF version on the JOSS site](https://github.com/openjournals/joss-papers/blob/joss.01554/joss.01554/10.21105.joss.01554.pdf).  Code-wise, I will need to merge https://github.com/UCBerkeleySETI/blimpy/pull/77 before I can work on the improvements to docstrings and missing argument descriptions that the referee highlighted. If you get a moment can you please take a look? You mentioned back in March that you thought some things might be hard to merge; it would be good to know if the latest updates I've made in the meantime address your concerns.

@marksbrt -- at the moment the tests aren't running on `calib_utils`. It would be great to get some basic tests running (which will require real data), and also getting your amazing PDF documentation linked up to the readthedocs!

**Comment by jeenriquez** [comment]
Thanks for all the good work Danny et al ! I'll be getting involved more on this in the next coming days.

**Comment by telegraphic** [comment]
Cheers Dr Enriquez 🎓

**Comment by jeenriquez** [comment]
I have now looked at the paper and did the last big merge (now to 1.4.0). I have also updated the PyPi. One more todo done! Let me know what else I can do to help.
